version: '3'
services:
  app-p-41:
    build: .
    volumes:
        - .:/usr/src

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq

volumes:
  rabbit:
